pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh '/usr/local/Cellar/maven/3.6.3/libexec/bin/mvn clean install --file ParkRide/pom.xml'
            }
        }
    }
} 
